### ISSUE TITLE
Spike: Create a customized codespace experience for running the echo example

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/examples#239]
The output goal of this spike is to use the "Open in Codespaces" badge in the echo README in order to give the best experience for running a wasmCloud application, for a new user to the page. If we like this experience, we should roll out a code space for each example

**Comment by connorsmith256** [comment]
@thomastaylor312 it's been a while since I thought about this. Do we still want this? If so, we should probably migrate it to the wasmCloud repo, right?

**Comment by thomastaylor312** [comment]
I'm honestly not sure if we still want it. Thoughts @brooksmtownsend?

**Comment by brooksmtownsend** [comment]
I don't see a real need here that would extend past just having a codespace in the wasmcloud/wasmcloud repo. Our examples should all include easy running instructions that would work inside of the codespace that we have set up, and I think that's all we really need here.

The original intent behind this issue was so that anyone could run an example without installing local tools, and so that would satisfy this requirement

**Comment by thomastaylor312** [comment]
So do we open a new issue with that as a requirement instead or just close for now and come back? I haven't heard of anyone really using the codespace yet, but that doesn't mean that they aren't
